title: hee611
logo: /assets/img/logo.jpg
email: th6116110@gmail.com
description: blog
favicon: true
color-scheme: auto
remote_theme : vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/hee611
    
navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
